name: 1_PC
channels:
  - conda-forge
  - defaults
dependencies: 
  - python=3.11.11 
  - pandas=2.2.3
  - pip 
  - pip: 
    - numpy
    - matplotlib
    - seaborn 
    - pybnesian
    - causal-learn
    - networkx 
    - ipykernel
    - jupyterlab


